server:
  port: 80
#=======================================================================================================================
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.3:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#=======================================================================================================================
knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway-service
