server:
  port: 80
#=======================================================================================================================
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.3:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: RequestRateLimiter
          args:
            deny-empty-key: false
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 50
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      database: 0
      host: 192.168.31.3
      port: 6379
      timeout: 5000
      password: redis
#=======================================================================================================================
knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway-service
#=======================================================================================================================
bucket4j:
  enabled: true
  filters:
    - cache-name: "ip-buckets"
      filter-method: gateway
      url: ".*"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 5
              time: 1
              unit: minutes