server:
  port: 15040
#=======================================================================================================================
spring:
  application:
    name: other-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.3:8848
#=======================================================================================================================
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'other-group'
      paths-to-match: '/**'
      packages-to-scan: 'io.github.hoooosi.imagehosting.controller'


