server:
  port: 15000
#=======================================================================================================================
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.3:8848
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.3:5432/simple_picture?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: postgres
    password: 123456
  data:
    redis:
      database: 0
      host: 192.168.31.3
      port: 6379
      timeout: 5000
      password: redis
#=======================================================================================================================
sa-token:
  max-login-count: 1
#=======================================================================================================================
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#=======================================================================================================================
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'user-group'
      paths-to-match: '/**'
      packages-to-scan: 'io.github.hoooosi.imagehosting.controller'


